title: Patrick Freyer
description: Personal website of Patrick Freyer, Software Developer & Technology Enthusiast
url: https://patrickfreyer.github.io
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Include processing
include:
  - _includes
  - _layouts
  - _data
  - assets
  - css

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - docs
  - test
  - tools
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Sass
sass:
  style: compressed

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: default 