#!/usr/bin/env node
/**
 * Copies third-party runtime deps out of node_modules into public/vendor/.
 *
 * Why this exists: the flight pages are classic (non-module) scripts that expect
 * `d3` and `topojson` as globals, so they cannot be bundled by Vite without
 * rewriting them. They were previously loaded from jsdelivr/cdnjs/fonts.googleapis
 * at runtime. Copying the builds locally keeps those scripts untouched while
 * removing every third-party request from the critical path.
 *
 * Be deliberate about WHAT gets copied. Naively copying @fontsource/inter ships
 * 253 files (7 subsets x 36 variants, 4.4 MB) for a site that renders latin text
 * at four weights; Font Awesome ships .ttf fallbacks no modern browser requests.
 *
 * public/vendor/ is generated, not committed - see .gitignore.
 */
import { mkdir, copyFile, rm, readdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const modules = join(root, 'node_modules');
const vendor = join(root, 'public', 'vendor');

const copy = async (from, to) => {
  const dest = join(vendor, to);
  await mkdir(dirname(dest), { recursive: true });
  await copyFile(join(modules, from), dest);
};

await rm(vendor, { recursive: true, force: true });

// ---- d3 + topojson: UMD builds, expose window globals ----------------------
await copy('d3/dist/d3.min.js', 'd3.min.js');
await copy('topojson-client/dist/topojson-client.min.js', 'topojson-client.min.js');

// ---- Font Awesome: woff2 only, and only the families actually used ---------
// The site uses `fas` (solid) and `fab` (brands). `far` (regular) is unused.
// all.min.css lists woff2 before ttf, so browsers never request the ttf.
// Keep FA's own css/ + webfonts/ layout: all.min.css references ../webfonts/,
// so flattening it to fontawesome/all.min.css silently 404s every glyph.
await copy('@fortawesome/fontawesome-free/css/all.min.css', 'fontawesome/css/all.min.css');
const faDir = '@fortawesome/fontawesome-free/webfonts';
for (const f of await readdir(join(modules, faDir))) {
  if (!f.endsWith('.woff2')) continue;
  if (!/fa-(solid|brands)-/.test(f)) continue;
  await copy(join(faDir, f), join('fontawesome/webfonts', f));
}

// ---- Inter: latin subset, four weights, woff2 ------------------------------
const WEIGHTS = [400, 500, 600, 700];
const faces = [];
for (const w of WEIGHTS) {
  const file = `inter-latin-${w}-normal.woff2`;
  await copy(`@fontsource/inter/files/${file}`, `inter/files/${file}`);
  faces.push(
    `@font-face {\n` +
    `  font-family: 'Inter';\n` +
    `  font-style: normal;\n` +
    `  font-weight: ${w};\n` +
    `  font-display: swap;\n` +
    `  src: url('./files/${file}') format('woff2');\n` +
    `  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6,\n` +
    `    U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122,\n` +
    `    U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;\n` +
    `}`,
  );
}
await writeFile(
  join(vendor, 'inter/inter.css'),
  `/* Generated by tools/vendor.mjs - do not edit. */\n${faces.join('\n\n')}\n`,
);

const count = async (d) =>
  (await readdir(join(vendor, d), { recursive: true })).length;
console.log(
  `vendored -> public/vendor/  ` +
  `(fontawesome: ${await count('fontawesome')} entries, inter: ${await count('inter')} entries)`,
);
